CREATE TABLE IF NOT EXISTS vital_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES workout_run(id_workout) ON DELETE CASCADE,
    exercise_id VARCHAR(255),
    heart_rate SMALLINT NOT NULL,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Policy to allow authenticated users to insert their own data would be managed in Supabase
-- Example: CREATE POLICY "Allow user insert" ON vital_signs FOR INSERT USING (auth.uid() = ...);
